export async function up(db) {
  await db.query(`
    CREATE TABLE IF NOT EXISTS BUKU (
      ID_BUKU INT AUTO_INCREMENT PRIMARY KEY,
      ID_TRANSAKSI INT,
      ID_REVIEW INT,
      ID_FAV INT,
      JUDUL VARCHAR(100),
      SLUG_BUKU VARCHAR(150),
      DESKRIPSI TEXT,
      COVER VARCHAR(255),
      HARGA INT,
      STATUS VARCHAR(20),
      FOREIGN KEY (ID_TRANSAKSI) REFERENCES TRANSAKSI(ID_TRANSAKSI),
      FOREIGN KEY (ID_REVIEW) REFERENCES REVIEW(ID_REVIEW),
      FOREIGN KEY (ID_FAV) REFERENCES FAVORITE(ID_FAV)
    ) ENGINE=InnoDB;
  `);
}

export async function down(db) {
  await db.query(`DROP TABLE IF EXISTS BUKU`);
}
